[package]
name = "rustvent"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "rustvent"
path = "src/lib.rs"

[[bin]]
name = "rustvent-cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
nalgebra = "0.32.3"
rayon = "1.8.0"
